USE [master]
GO

/****** Object:  Database [HomeSwitchHome]    Script Date: 17/5/2019 22:55:45 ******/
CREATE DATABASE [HomeSwitchHome]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HomeSwitchHome', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HomeSwitchHome.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HomeSwitchHome_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\HomeSwitchHome_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HomeSwitchHome].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HomeSwitchHome] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET ARITHABORT OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HomeSwitchHome] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HomeSwitchHome] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HomeSwitchHome] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HomeSwitchHome] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HomeSwitchHome] SET  MULTI_USER 
GO

ALTER DATABASE [HomeSwitchHome] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HomeSwitchHome] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HomeSwitchHome] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HomeSwitchHome] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HomeSwitchHome] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HomeSwitchHome] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HomeSwitchHome] SET  READ_WRITE 
GO