CREATE TABLE [dbo].[PUJA](
	[IdPuja] [int] NOT NULL,
	[IdSubasta] [int] NOT NULL,
	[IdCliente] [int] NOT NULL,
	[Monto] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdPuja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUJA]  WITH CHECK ADD FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO
ALTER TABLE [dbo].[PUJA]  WITH CHECK ADD FOREIGN KEY([IdSubasta])
REFERENCES [dbo].[SUBASTA] ([IdSubasta])
GO